name: Publish info page

on:
  push:
    branches:
      - master
    paths:
      - 'info_page/src/**'

jobs:
  deploy:
    name: Build and deploy to gh-pages branch
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install
    - name: Deploy
      uses: s0/git-publish-subdir-action@v2.0.0
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: info_page/dist
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
